### ISSUE TITLE
Adrien's issue

### ISSUE THREAD

**Issue by aallorant** [math241s24/project01-ojkp#3]
---
name: Adrien's review
about: Review of project proposal
title: Proposal review
---

Your proposal is excellent! I am really looking forward to seeing the results.

### proposal.qmd

- Everything runs correctly and the proposal reads really well

### about.qmd

You want to update the `About` section of your website.
  
### _quarto.yml

You want to update the `yml` document.

Specifically, you want to update the website section of the `yml`:

```
website:
  title: Seattle Bike
  navbar:
    right:
      - icon: github
        href: https://github.com/aallorant/project01-seattle-bike
```
